"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$username\
$hostname\
$directory$git_branch\
$git_state\
$git_status\
$cmd_duration\
$character"""

[directory]
style = "yellow"

[character]
success_symbol = " [\\$](white)"
error_symbol = " [\\$](red)"

[git_branch]
style = ""
format = "[@$branch]($style)"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style)"
style = ""
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = ""

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
