(defun split-window-right-and-switch ()
  (interactive)
  (split-window-right)
  (other-window 1)
  )
(defun split-window-below-and-switch ()
  (interactive)
  (split-window-below)
  (other-window 1)
  )
