# # Load Antigen
source ~/.zsh/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Antigen Bundles
antigen bundle git-extras                          # extra git commands
antigen bundle ssh-agent                           # For SSH, starting ssh-agent is annoying
# antigen bundle zsh-users/zsh-syntax-highlighting   # Syntax highlighting bundle.

# OS specific bundles
if [[ $CURRENT_OS == 'OS X' ]]; then
  antigen bundle brew
fi

# Tell antigen that you're done.
antigen apply

# Theme
source ~/.zsh/angelcarballo.zsh-theme

# Aliases
source ~/.bash_aliases

# Vim everywhere
bindkey -v
export VISUAL=vim
export EDITOR=vim
export KEYTIMEOUT=1  # reduce delay when changing modes

# Custom functions
source ~/.zsh/custom-functions.zsh

# Custom emacs-like bindings (useful on insert mode)
bindkey '^b' beginning-of-line
bindkey '^e' end-of-line
bindkey '^w' backward-kill-word


# Altern between foreground/background with Ctrl-z (see custom-functions.zsh)
bindkey '^z' fancy-ctrl-z

# Complete words from tmux pane(s)
bindkey '^xt' tmux-pane-words-prefix
bindkey '^x^x' tmux-pane-words-anywhere

# ctrl-r starts searching history backward
bindkey '^r' history-incremental-search-backward

# easier cd into frequent directories
setopt auto_cd
cdpath=($HOME/src)

# dont share history
setopt no_share_history

# Paths common to all platforms
export PATH="$HOME/bin:$HOME/src/dotfiles/bin:$HOME/.rbenv/bin:$PATH"

# Fix bug when passing arguments to rake
unsetopt nomatch

# Ensure there is a valid temp dir for vim
if [[ ! -d "$TMPDIR"  ]]; then
  export TMPDIR="/tmp/`whoami`"
  mkdir -p -m 700 "$TMPDIR"
fi

# Enable rbenv
eval "$(rbenv init -)"

# Source local config if present
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# Source fzf fuzzy finder configuration is present
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Try to use Ag as default fzf command
 export FZF_DEFAULT_COMMAND='ag -g ""'
