# # Load Antigen
source ~/.zsh/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Antigen Bundles
antigen bundle git-extras                          # extra git commands
antigen bundle ssh-agent                           # For SSH, starting ssh-agent is annoying
antigen bundle zsh-users/zsh-syntax-highlighting   # Syntax highlighting bundle.

# OS specific bundles
if [[ $CURRENT_OS == 'OS X' ]]; then
  antigen bundle brew
fi

# Tell antigen that you're done.
antigen apply

# Theme
source ~/.zsh/angelcarballo.zsh-theme

# Aliases
source ~/.bash_aliases

# Vim everywhere
bindkey -v
export VISUAL=vim
export EDITOR=vim
export KEYTIMEOUT=1  # reduce delay when changing modes

# ctrl-w removed word backwards
bindkey '^w' backward-kill-word

# ctrl-r starts searching history backward
bindkey '^r' history-incremental-search-backward

# easier cd into frequent directories
setopt auto_cd
cdpath=($HOME/thoughtbot $HOME/src)

# dont share history
setopt no_share_history

# Paths common to all platforms
export PATH="$HOME/bin:$HOME/src/dotfiles/bin:$HOME/.rbenv/bin:$PATH"

# Enable rbenv
eval "$(rbenv init -)"

# Load local config if present
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

