# # Load Antigen
source ~/.zsh/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Antigen Bundles
antigen bundle git-extras                          # extra git commands
antigen bundle web-search                          # adds google cmd
antigen bundle ssh-agent                           # For SSH, starting ssh-agent is annoying
antigen bundle zsh-users/zsh-syntax-highlighting   # Syntax highlighting bundle.

# OS specific bundles
if [[ $CURRENT_OS == 'OS X' ]]; then
  antigen bundle brew
fi


# Tell antigen that you're done.
antigen apply

# Pure theme
source ~/.zsh/async.zsh
source ~/.zsh/pure.zsh

# Aliases
source ~/.bash_aliases

# Vim everywhere
set -o vi
export EDITOR=vim

# Paths common to all platforms
export PATH="$HOME/bin:$HOME/src/dotfiles/bin:$HOME/.rbenv/bin:$PATH"
