### Alias

# Comunes
alias c='clear'
alias celar='clear'
alias ll='ls -lh'

# Atajos Mac
alias flushdns='dscacheutil -flushcache'

# Rails
alias brake='bundle exec rake'
alias bi='bundle install'
alias be='bundle exec'
alias ber='bundle exec rspec --color'
alias bers='bundle exec spring rspec --color'
alias berf='bundle exec rspec --color --fail-fast'
alias rs='bundle exec rails server'
alias rsd='bundle exec rails server --debugger'
alias rc='bundle exec rails console'
alias rg='bundle exec rails generate '
alias migrate='bundle exec rake db:migrate && bundle exec rake db:test:prepare'
alias deploy='bundle exec cap deploy'
alias deploym='bundle exec cap deploy:migrate'

# Git
alias gs='git status'
alias gp='git pull'
alias gf='git fetch'
alias gl='git log --oneline --decorate --graph --all'
alias gll="git log --pretty=format:'%h - %an [%ar] %s'"
alias gsm='git log -E -i --grep '
alias gsc='git log -S '
alias gps='git push'
alias ga='git add -A .'
alias gc='git commit'
alias gca='git commit -a'
alias gcm='git commit -m '
alias gcam='git commit -a -m '
alias gb='git branch'
alias gd='git diff'
alias gdh='git diff HEAD'
alias gco='git checkout '
alias gcb='git checkout -b'
alias gclean='git clean -fd'
alias gr='git reset --hard HEAD'
alias go='git open'
alias gom='git open origin master'
alias grl='git reflog'

# Tmux
alias tks='tmux kill-session -t '

# Docker & boot2docker
alias dockerenv='eval `boot2docker shellinit 2>/dev/null`'

# Vim
alias vim='/usr/local/bin/vim'
alias v='vim .'

# Emacs/Spacemacs
alias s='emacs .'

