### Alias

# Comunes
alias c='clear'
alias ll='ls -l'
alias ll='ls -l'

# Atajos Mac
alias flushdns='dscacheutil -flushcache'

# Rails
alias be='bundle exec'
alias rs='bundle exec rails s'
alias rsd='bundle exec rails s --debugger'
alias rc='bundle exec rails c'
alias migrate='bundle exec rake db:migrate'
alias deploy='bundle exec cap deploy'
alias deploym='bundle exec cap deploy:migrate'

# Git
alias gs='git status'
alias gp='git pull'
alias gps='git push'
alias ga='git add -A .'
alias gc='git ci -m'
alias gca='git ci -a -m'
